server:
  port: ${PORT:8080}
  servlet:
    context-path: /api

spring:
  application:
    name: spares-hub-server
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
